const ACCESS_LOGIN_INIT = 'ACCESS_LOGIN_INIT';
const ACCESS_LOGIN_FINISH = 'ACCESS_LOGIN_FINISH';
const USER_LOGOUT = 'USER_LOGOUT';



export {
    ACCESS_LOGIN_INIT,
    ACCESS_LOGIN_FINISH,
    USER_LOGOUT
};
